name: Download playlist data

on:
  workflow_dispatch:
  schedule:
    - cron: '15 3 * * 1'

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: setup-r
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.2'

      - name: Install libcurl
        run: sudo apt-get install libcurl4-openssl-dev

      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('renv'); renv::restore(confirm = FALSE)"
      - name: Check DB
        run: Rscript -e 'file.exists("data_2020.sqlite")'
      - name: Check connection
        run: Rscript -e 'library(RSQLite);con <- dbConnect(SQLite(), "data_2020.sqlite");o <- dbGetQuery(con, "select count(*) from playlist");print(o);dbDisconnect(con)'
      - name: Scrape playlist data from the Czech Radio's API
        run: Rscript 00_get_radio_data.R

      - name: Scrape data on new tracks and interprets from Spotify 
        run: Rscript 00_get_spotify_data.R
        env: 
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}

      - name: Commit and push
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "Add data from last week" || exit 0
          git push